# Generated by Django 3.2.19 on 2023-05-04 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('01', 'Stakeholders Being Hired In Customer Accounts'), ('02', 'Stakeholders Leaving Customer Accounts'), ('03', 'Customers Moving Into Prospect Accounts'), ('04', 'Customers Moving Into Greenfield Accounts'), ('05', 'Stakeholders Being Hired In Prospect Accounts')], max_length=2)),
                ('stakeholder_current_company', models.CharField(max_length=255)),
                ('stakeholder_first_name', models.CharField(max_length=128)),
                ('stakeholder_last_name', models.CharField(blank=True, max_length=128)),
                ('stakeholder_current_title', models.CharField(max_length=255)),
                ('stakeholder_time_in_current_role', models.CharField(max_length=255)),
                ('stakeholder_current_email', models.CharField(max_length=255)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.client')),
            ],
        ),
    ]
