# Generated by Django 3.2.19 on 2023-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='stakeholder_phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='stakeholder_last_name',
            field=models.CharField(max_length=128),
        ),
    ]
